export const LIST_PAGE_LOADED = "LIST_PAGE_LOADED";
export const SEARCH_TEXT_CHANGE = "SEARCH_TEXT_CHANGE";
export const SHOW_DROP_TOGGLE = "SHOW_DROP_TOGGLE";
export const ASYNC_TOGGLE = "ASYNC_TOGGLE";
export const GET_EMPLOYEE = "GET_EMPLOYEE";
